export const attachmentsActionsTypes = {
    GET_ATTACHEMENTS_REQUEST: 'GET_ATTACHEMENTS_REQUEST',
    GET_ATTACHEMENTS_SUCCESS: 'GET_ATTACHEMENTS_SUCCESS',
    GET_ATTACHEMENTS_FAILURE: 'GET_ATTACHEMENTS_FAILURE',

    CREATE_ATTACHEMENT_REQUEST: 'CREATE_ATTACHEMENT_REQUEST',
    CREATE_ATTACHEMENT_SUCCESS: 'CREATE_ATTACHEMENT_SUCCESS',
    CREATE_ATTACHEMENT_FAILURE: 'CREATE_ATTACHEMENT_FAILURE',

    DELETE_ATTACHEMENT_REQUEST: 'DELETE_ATTACHEMENT_REQUEST',
    DELETE_ATTACHEMENT_SUCCESS: 'DELETE_ATTACHEMENT_SUCCESS',
    DELETE_ATTACHEMENT_FAILURE: 'DELETE_ATTACHEMENT_FAILURE'
};