export const attachmentsActionsTypes = {
    GET_ATTACHEMENTS_REQUEST: 'GET_ATTACHEMENTS_REQUEST',
    GET_ATTACHEMENTS_SUCCESS: 'GET_ATTACHEMENTS_SUCCESS',
    GET_ATTACHEMENTS_FAILURE: 'GET_ATTACHEMENTS_FAILURE'
};