export const authActionsTypes = {
    GET_AUTH_REQUEST: 'GET_AUTH_REQUEST',
    GET_AUTH_SUCCESS: 'GET_AUTH_SUCCESS',
    GET_AUTH_FAILURE: 'GET_AUTH_FAILURE',

    GET_FNS_PUBLIC_KEY_REQUEST: 'GET_FNS_PUBLIC_KEY_REQUEST',
    GET_FNS_PUBLIC_KEY_SUCCESS: 'GET_FNS_PUBLIC_KEY_SUCCESS',
    GET_FNS_PUBLIC_KEY_FAILURE: 'GET_FNS_PUBLIC_KEY_FAILURE'
};
