export const cloudsActionsTypes = {
  GET_LOCAL_CLOUDS_REQUEST: 'GET_LOCAL_CLOUDS_REQUEST',
  GET_LOCAL_CLOUDS_SUCCESS: 'GET_LOCAL_CLOUDS_SUCCESS',
  GET_LOCAL_CLOUDS_FAILURE: 'GET_LOCAL_CLOUDS_FAILURE',

  GET_REMOTE_CLOUDS_REQUEST: 'GET_REMOTE_CLOUDS_REQUEST',
  GET_REMOTE_CLOUDS_SUCCESS: 'GET_REMOTE_CLOUDS_SUCCESS',
  GET_REMOTE_CLOUDS_FAILURE: 'GET_REMOTE_CLOUDS_FAILURE',

  GET_MEMBER_CLOUDS_REQUEST: 'GET_MEMBER_CLOUDS_REQUEST',
  GET_MEMBER_CLOUDS_SUCCESS: 'GET_MEMBER_CLOUDS_SUCCESS',
  GET_MEMBER_CLOUDS_FAILURE: 'GET_MEMBER_CLOUDS_FAILURE',
};
