export const computesActionsTypes = {
  GET_COMPUTES_REQUEST: 'GET_COMPUTES_REQUEST',
  GET_COMPUTES_SUCCESS: 'GET_COMPUTES_SUCCESS',
  GET_COMPUTES_FAILURE: 'GET_COMPUTES_FAILURE',

  GET_DATA_COMPUTE_REQUEST: 'GET_DATA_COMPUTE_REQUEST',
  GET_DATA_COMPUTE_SUCCESS: 'GET_DATA_COMPUTE_SUCCESS',
  GET_DATA_COMPUTE_FAILURE: 'GET_DATA_COMPUTE_FAILURE',

  GET_IMAGES_REQUEST: 'GET_IMAGES_REQUEST',
  GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
  GET_IMAGES_FAILURE: 'GET_IMAGES_FAILURE',

  GET_REMOTE_IMAGES_REQUEST: 'GET_REMOTE_IMAGES_REQUEST',
  GET_REMOTE_IMAGES_SUCCESS: 'GET_REMOTE_IMAGES_SUCCESS',
  GET_REMOTE_IMAGES_FAILURE: 'GET_REMOTE_IMAGES_FAILURE',

  CREATE_COMPUTE_REQUEST: 'CREATE_COMPUTE_REQUEST',
  CREATE_COMPUTE_SUCCESS: 'CREATE_COMPUTE_SUCCESS',
  CREATE_COMPUTE_FAILURE: 'CREATE_COMPUTE_FAILURE',

  DELETE_COMPUTE_REQUEST: 'DELETE_COMPUTE_REQUEST',
  DELETE_COMPUTE_SUCCESS: 'DELETE_COMPUTE_SUCCESS',
  DELETE_COMPUTE_FAILURE: 'DELETE_COMPUTE_FAILURE',

  GET_COMPUTE_ALLOCATION_REQUEST: 'GET_COMPUTE_ALLOCATION_REQUEST',
  GET_COMPUTE_ALLOCATION_SUCCESS: 'GET_COMPUTE_ALLOCATION_SUCCESS',
  GET_COMPUTE_ALLOCATION_FAILURE: 'GET_COMPUTE_ALLOCATION_FAILURE',

  GET_ALL_COMPUTE_ALLOCATION_REQUEST: 'GET_ALL_COMPUTE_ALLOCATION_REQUEST',
  GET_ALL_COMPUTE_ALLOCATION_SUCCESS: 'GET_ALL_COMPUTE_ALLOCATION_SUCCESS',
  GET_ALL_COMPUTE_ALLOCATION_FAILURE: 'GET_ALL_COMPUTE_ALLOCATION_FAILURE',

  PAUSE_COMPUTE_REQUEST: 'PAUSE_COMPUTE_REQUEST',
  PAUSE_COMPUTE_SUCCESS: 'PAUSE_COMPUTE_SUCCESS',
  PAUSE_COMPUTE_FAILURE: 'PAUSE_COMPUTE_FAILURE',

  HIBERNATE_COMPUTE_REQUEST: 'HIBERNATE_COMPUTE_REQUEST',
  HIBERNATE_COMPUTE_SUCCESS: 'HIBERNATE_COMPUTE_SUCCESS',
  HIBERNATE_COMPUTE_FAILURE: 'HIBERNATE_COMPUTE_FAILURE',
  
};
