export const computesActionsTypes = {
    GET_COMPUTES_REQUEST: 'GET_COMPUTES_REQUEST',
    GET_COMPUTES_SUCCESS: 'GET_COMPUTES_SUCCESS',
    GET_COMPUTES_FAILURE: 'GET_COMPUTES_FAILURE',


    GET_IMAGES_REQUEST: 'GET_IMAGES_REQUEST',
    GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
    GET_IMAGES_FAILURE: 'GET_IMAGES_FAILURE',
};