export const computesActionsTypes = {
  GET_COMPUTES_REQUEST: 'GET_COMPUTES_REQUEST',
  GET_COMPUTES_SUCCESS: 'GET_COMPUTES_SUCCESS',
  GET_COMPUTES_FAILURE: 'GET_COMPUTES_FAILURE',

  GET_DATA_COMPUTE_REQUEST: 'GET_DATA_COMPUTE_REQUEST',
  GET_DATA_COMPUTE_SUCCESS: 'GET_DATA_COMPUTE_SUCCESS',
  GET_DATA_COMPUTE_FAILURE: 'GET_DATA_COMPUTE_FAILURE',

  GET_IMAGES_REQUEST: 'GET_IMAGES_REQUEST',
  GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
  GET_IMAGES_FAILURE: 'GET_IMAGES_FAILURE',

  GET_REMOTE_IMAGES_REQUEST: 'GET_REMOTE_IMAGES_REQUEST',
  GET_REMOTE_IMAGES_SUCCESS: 'GET_REMOTE_IMAGES_SUCCESS',
  GET_REMOTE_IMAGES_FAILURE: 'GET_REMOTE_IMAGES_FAILURE',

  CREATE_COMPUTE_REQUEST: 'CREATE_COMPUTE_REQUEST',
  CREATE_COMPUTE_SUCCESS: 'CREATE_COMPUTE_SUCCESS',
  CREATE_COMPUTE_FAILURE: 'CREATE_COMPUTE_FAILURE',

  DELETE_COMPUTE_REQUEST: 'DELETE_COMPUTE_REQUEST',
  DELETE_COMPUTE_SUCCESS: 'DELETE_COMPUTE_SUCCESS',
  DELETE_COMPUTE_FAILURE: 'DELETE_COMPUTE_FAILURE'
};
