export const floatIpsActionsTypes = {
    GET_FLOAT_IPS_REQUEST: 'GET_FLOAT_IPS_REQUEST',
    GET_FLOAT_IPS_SUCCESS: 'GET_FLOAT_IPS_SUCCESS',
    GET_FLOAT_IPS_FAILURE: 'GET_FLOAT_IPS_FAILURE',

    CREATE_FLOAT_IP_REQUEST: 'CREATE_FLOAT_IP_REQUEST',
    CREATE_FLOAT_IP_SUCCESS: 'CREATE_FLOAT_IP_SUCCESS',
    CREATE_FLOAT_IP_FAILURE: 'CREATE_FLOAT_IP_FAILURE',
};