export const membersActionsTypes = {
  GET_MEMBERS_REQUEST: 'GET_MEMBERS_REQUEST',
  GET_MEMBERS_SUCCESS: 'GET_MEMBERS_SUCCESS',
  GET_MEMBERS_FAILURE: 'GET_MEMBERS_FAILURE',

  GET_MEMBER_DATA_REQUEST: 'GET_MEMBER_DATA_REQUEST',
  GET_MEMBER_DATA_SUCCESS: 'GET_MEMBER_DATA_SUCCESS',
  GET_MEMBER_DATA_FAILURE: 'GET_MEMBER_DATA_FAILURE',

  GET_ALL_MEMBERS_DATA_REQUEST: 'GET_ALL_MEMBERS_DATA_REQUEST',
  GET_ALL_MEMBERS_DATA_SUCCESS: 'GET_ALL_MEMBERS_DATA_SUCCESS',
  GET_ALL_MEMBERS_DATA_FAILURE: 'GET_ALL_MEMBERS_DATA_FAILURE',
};
