export const networksActionsTypes = {
    GET_NETWORKS_REQUEST: 'GET_NETWORKS_REQUEST',
    GET_NETWORKS_SUCCESS: 'GET_NETWORKS_SUCCESS',
    GET_NETWORKS_FAILURE: 'GET_NETWORKS_FAILURE',

    CREATE_NETWORK_REQUEST: 'CREATE_NETWORK_REQUEST',
    CREATE_NETWORK_SUCCESS: 'CREATE_NETWORK_SUCCESS',
    CREATE_NETWORK_FAILURE: 'CREATE_NETWORK_FAILURE'
};