export const networksActionsTypes = {
    GET_NETWORKS_REQUEST: 'GET_NETWORKS_REQUEST',
    GET_NETWORKS_SUCCESS: 'GET_NETWORKS_SUCCESS',
    GET_NETWORKS_FAILURE: 'GET_NETWORKS_FAILURE',

    GET_DATA_NETWORK_REQUEST: 'GET_DATA_NETWORK_REQUEST',
    GET_DATA_NETWORK_SUCCESS: 'GET_DATA_NETWORK_SUCCESS',
    GET_DATA_NETWORK_FAILURE: 'GET_DATA_NETWORK_FAILURE',

    CREATE_NETWORK_REQUEST: 'CREATE_NETWORK_REQUEST',
    CREATE_NETWORK_SUCCESS: 'CREATE_NETWORK_SUCCESS',
    CREATE_NETWORK_FAILURE: 'CREATE_NETWORK_FAILURE',

    DELETE_NETWORK_REQUEST: 'DELETE_NETWORK_REQUEST',
    DELETE_NETWORK_SUCCESS: 'DELETE_NETWORK_SUCCESS',
    DELETE_NETWORK_FAILURE: 'DELETE_NETWORK_FAILURE',

    GET_FED_NETWORKS_REQUEST: 'GET_FED_NETWORKS_REQUEST',
    GET_FED_NETWORKS_SUCCESS: 'GET_FED_NETWORKS_SUCCESS',
    GET_FED_NETWORKS_FAILURE: 'GET_FED_NETWORKS_FAILURE',

    GET_FED_DATA_NETWORK_REQUEST: 'GET_DATA_NETWORK_REQUEST',
    GET_FED_DATA_NETWORK_SUCCESS: 'GET_DATA_NETWORK_SUCCESS',
    GET_FED_DATA_NETWORK_FAILURE: 'GET_DATA_NETWORK_FAILURE',

    CREATE_FED_NETWORK_REQUEST: 'CREATE_FED_NETWORK_REQUEST',
    CREATE_FED_NETWORK_SUCCESS: 'CREATE_FED_NETWORK_SUCCESS',
    CREATE_FED_NETWORK_FAILURE: 'CREATE_FED_NETWORK_FAILURE',

    DELETE_FED_NETWORK_REQUEST: 'DELETE_FED_NETWORK_REQUEST',
    DELETE_FED_NETWORK_SUCCESS: 'DELETE_FED_NETWORK_SUCCESS',
    DELETE_FED_NETWORK_FAILURE: 'DELETE_FED_NETWORK_FAILURE',

    CREATE_NETWORK_SECURITY_RULE_REQUEST: 'CREATE_NETWORK_SECURITY_RULE_REQUEST',
    CREATE_NETWORK_SECURITY_RULE_SUCCESS: 'CREATE_NETWORK_SECURITY_RULE_SUCCESS',
    CREATE_NETWORK_SECURITY_RULE_FAILURE: 'CREATE_NETWORK_SECURITY_RULE_FAILURE',

    GET_NETWORK_SECURITY_RULES_REQUEST: 'GET_NETWORK_SECURITY_RULES_REQUEST',
    GET_NETWORK_SECURITY_RULES_SUCCESS: 'GET_NETWORK_SECURITY_RULES_SUCCESS',
    GET_NETWORK_SECURITY_RULES_FAILURE: 'GET_NETWORK_SECURITY_RULES_FAILURE',

    DELETE_NETWORK_SECURITY_RULE_REQUEST: 'DELETE_NETWORK_SECURITY_RULE_REQUEST',
    DELETE_NETWORK_SECURITY_RULE_SUCCESS: 'DELETE_NETWORK_SECURITY_RULE_SUCCESS',
    DELETE_NETWORK_SECURITY_RULE_FAILURE: 'DELETE_NETWORK_SECURITY_RULE_FAILURE',

    GET_NETWORK_ALLOCATION_REQUEST: 'GET_NETWORK_ALLOCATION_REQUEST',
    GET_NETWORK_ALLOCATION_SUCCESS: 'GET_NETWORK_ALLOCATION_SUCCESS',
    GET_NETWORK_ALLOCATION_FAILURE: 'GET_NETWORK_ALLOCATION_FAILURE',

    GET_ALL_NETWORK_ALLOCATION_REQUEST: 'GET_ALL_NETWORK_ALLOCATION_REQUEST',
    GET_ALL_NETWORK_ALLOCATION_SUCCESS: 'GET_ALL_NETWORK_ALLOCATION_SUCCESS',
    GET_ALL_NETWORK_ALLOCATION_FAILURE: 'GET_ALL_NETWORK_ALLOCATION_FAILURE'
};
