export const networksActionsTypes = {
    GET_NETWORKS_REQUEST: 'GET_NETWORKS_REQUEST',
    GET_NETWORKS_SUCCESS: 'GET_NETWORKS_SUCCESS',
    GET_NETWORKS_FAILURE: 'GET_NETWORKS_FAILURE',

    GET_DATA_NETWORK_REQUEST: 'GET_DATA_NETWORK_REQUEST',
    GET_DATA_NETWORK_SUCCESS: 'GET_DATA_NETWORK_SUCCESS',
    GET_DATA_NETWORK_FAILURE: 'GET_DATA_NETWORK_FAILURE',

    CREATE_NETWORK_REQUEST: 'CREATE_NETWORK_REQUEST',
    CREATE_NETWORK_SUCCESS: 'CREATE_NETWORK_SUCCESS',
    CREATE_NETWORK_FAILURE: 'CREATE_NETWORK_FAILURE',

    DELETE_NETWORK_REQUEST: 'DELETE_NETWORK_REQUEST',
    DELETE_NETWORK_SUCCESS: 'DELETE_NETWORK_SUCCESS',
    DELETE_NETWORK_FAILURE: 'DELETE_NETWORK_FAILURE',

    GET_FED_NETWORKS_REQUEST: 'GET_FED_NETWORKS_REQUEST',
    GET_FED_NETWORKS_SUCCESS: 'GET_FED_NETWORKS_SUCCESS',
    GET_FED_NETWORKS_FAILURE: 'GET_FED_NETWORKS_FAILURE',

    GET_FED_DATA_NETWORK_REQUEST: 'GET_DATA_NETWORK_REQUEST',
    GET_FED_DATA_NETWORK_SUCCESS: 'GET_DATA_NETWORK_SUCCESS',
    GET_FED_DATA_NETWORK_FAILURE: 'GET_DATA_NETWORK_FAILURE',

    CREATE_FED_NETWORK_REQUEST: 'CREATE_FED_NETWORK_REQUEST',
    CREATE_FED_NETWORK_SUCCESS: 'CREATE_FED_NETWORK_SUCCESS',
    CREATE_FED_NETWORK_FAILURE: 'CREATE_FED_NETWORK_FAILURE',

    DELETE_FED_NETWORK_REQUEST: 'DELETE_FED_NETWORK_REQUEST',
    DELETE_FED_NETWORK_SUCCESS: 'DELETE_FED_NETWORK_SUCCESS',
    DELETE_FED_NETWORK_FAILURE: 'DELETE_FED_NETWORK_FAILURE',
};