export const providersActionsTypes = {
  GET_PROVIDERS_REQUEST: 'GET_PROVIDERS_REQUEST',
  GET_PROVIDERS_SUCCESS: 'GET_PROVIDERS_SUCCESS',
  GET_PROVIDERS_FAILURE: 'GET_PROVIDERS_FAILURE',

  GET_PROVIDER_DATA_REQUEST: 'GET_PROVIDER_DATA_REQUEST',
  GET_PROVIDER_DATA_SUCCESS: 'GET_PROVIDER_DATA_SUCCESS',
  GET_PROVIDER_DATA_FAILURE: 'GET_PROVIDER_DATA_FAILURE',

  GET_ALL_PROVIDERS_DATA_REQUEST: 'GET_ALL_PROVIDERS_DATA_REQUEST',
  GET_ALL_PROVIDERS_DATA_SUCCESS: 'GET_ALL_PROVIDERS_DATA_SUCCESS',
  GET_ALL_PROVIDERS_DATA_FAILURE: 'GET_ALL_PROVIDERS_DATA_FAILURE',
};
