export const publicIpsActionsTypes = {
    GET_PUBLIC_IPS_REQUEST: 'GET_PUBLIC_IPS_REQUEST',
    GET_PUBLIC_IPS_SUCCESS: 'GET_PUBLIC_IPS_SUCCESS',
    GET_PUBLIC_IPS_FAILURE: 'GET_PUBLIC_IPS_FAILURE',

    CREATE_PUBLIC_IP_REQUEST: 'CREATE_PUBLIC_IP_REQUEST',
    CREATE_PUBLIC_IP_SUCCESS: 'CREATE_PUBLIC_IP_SUCCESS',
    CREATE_PUBLIC_IP_FAILURE: 'CREATE_PUBLIC_IP_FAILURE',

    GET_DATA_PUBLIC_IP_REQUEST: 'GET_DATA_PUBLIC_IP_REQUEST',
    GET_DATA_PUBLIC_IP_SUCCESS: 'GET_DATA_PUBLIC_IP_SUCCESS',
    GET_DATA_PUBLIC_IP_FAILURE: 'GET_DATA_PUBLIC_IP_FAILURE',

    DELETE_PUBLIC_IP_REQUEST: 'DELETE_PUBLIC_IP_REQUEST',
    DELETE_PUBLIC_IP_SUCCESS: 'DELETE_PUBLIC_IP_SUCCESS',
    DELETE_PUBLIC_IP_FAILURE: 'DELETE_PUBLIC_IP_FAILURE',

    CREATE_PUBLIC_IP_SECURITY_RULES_REQUEST: 'CREATE_PUBLIC_IP_SECURITY_RULES_REQUEST',
    CREATE_PUBLIC_IP_SECURITY_RULES_SUCCESS: 'CREATE_PUBLIC_IP_SECURITY_RULES_SUCCESS',
    CREATE_PUBLIC_IP_SECURITY_RULES_FAILURE: 'CREATE_PUBLIC_IP_SECURITY_RULES_FAILURE',

    GET_PUBLIC_IP_SECURITY_RULES_REQUEST: 'GET_PUBLIC_IP_SECURITY_RULES_REQUEST',
    GET_PUBLIC_IP_SECURITY_RULES_SUCCESS: 'GET_PUBLIC_IP_SECURITY_RULES_SUCCESS',
    GET_PUBLIC_IP_SECURITY_RULES_FAILURE: 'GET_PUBLIC_IP_SECURITY_RULES_FAILURE',

    DELETE_PUBLIC_IP_SECURITY_RULE_REQUEST: 'DELETE_PUBLIC_IP_SECURITY_RULE_REQUEST',
    DELETE_PUBLIC_IP_SECURITY_RULE_SUCCESS: 'DELETE_PUBLIC_IP_SECURITY_RULE_SUCCESS',
    DELETE_PUBLIC_IP_SECURITY_RULE_FAILURE: 'DELETE_PUBLIC_IP_SECURITY_RULE_FAILURE',
};
