export const volumesActionsTypes = {
    GET_VOLUMES_REQUEST: 'GET_VOLUMES_REQUEST',
    GET_VOLUMES_SUCCESS: 'GET_VOLUMES_SUCCESS',
    GET_VOLUMES_FAILURE: 'GET_VOLUMES_FAILURE',

    CREATE_VOLUME_REQUEST: 'CREATE_VOLUME_REQUEST',
    CREATE_VOLUME_SUCCESS: 'CREATE_VOLUME_SUCCESS',
    CREATE_VOLUME_FAILURE: 'CREATE_VOLUME_FAILURE',

    GET_DATA_VOLUME_REQUEST: 'GET_DATA_VOLUME_REQUEST',
    GET_DATA_VOLUME_SUCCESS: 'GET_DATA_VOLUME_SUCCESS',
    GET_DATA_VOLUME_FAILURE: 'GET_DATA_VOLUME_FAILURE',

    DELETE_VOLUME_REQUEST: 'DELETE_VOLUME_REQUEST',
    DELETE_VOLUME_SUCCESS: 'DELETE_VOLUME_SUCCESS',
    DELETE_VOLUME_FAILURE: 'DELETE_VOLUME_FAILURE',

    GET_VOLUME_ALLOCATION_REQUEST: 'GET_VOLUME_ALLOCATION_REQUEST',
    GET_VOLUME_ALLOCATION_SUCCESS: 'GET_VOLUME_ALLOCATION_SUCCESS',
    GET_VOLUME_ALLOCATION_FAILURE: 'GET_VOLUME_ALLOCATION_FAILURE',

    GET_ALL_VOLUME_ALLOCATION_REQUEST: 'GET_ALL_VOLUME_ALLOCATION_REQUEST',
    GET_ALL_VOLUME_ALLOCATION_SUCCESS: 'GET_ALL_VOLUME_ALLOCATION_SUCCESS',
    GET_ALL_VOLUME_ALLOCATION_FAILURE: 'GET_ALL_VOLUME_ALLOCATION_FAILURE'
};