#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <git branch> <docker_tag>"
  exit 1
fi

branch=$1
docker_tag=$2
sudo docker build --build-arg BRANCH=$branch --no-cache -t fogbow/fogbow-gui:$docker_tag .
